packages:
  - apps/**
  - packages/**
catalog:
  vite: ^6.2.0
  react: ^19.0.0
  react-dom: ^19.0.0

  # devDependencies
  typescript: ^5.8.2
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react-swc": ^3.8.0
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
